spring:
  application:
    name: Tourism forum

  datasource:
    url: jdbc:postgresql://localhost:5432/tourism-forum
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: info
  file:
    name: forum-log.txt
    path: /

server:
  port: 8080